import { Language } from 'src/common/constants';

export const labModuleSeed = [
  {
    name: 'Pengukuran Angka Penting',
    code: 'PAP',
    language: Language.ID,
    journal_cover_url:
      'https://docs.google.com/document/d/1g3EL4F-CNn7Ai91cGEKoE0o6iCBWDRvO/edit?usp=sharing\u0026ouid=107672459749284549879\u0026rtpof=true\u0026sd=true',
    isActive: true,
    pretask_url: null,
    is_pretask_visible: true,
    video_url: 'https://youtu.be/zpuMpagyBZA',
    is_video_visible: true,
    simulator_url:
      'https://drive.google.com/file/d/1iY_oFShVeeF-sj2geC32E5Gd_t6x1ICD/view?usp=sharing',
    is_simulator_visible: true,
  },
  {
    name: 'Measurement and Significant Figures',
    code: 'PAP',
    language: Language.EN,
    journal_cover_url: null,
    isActive: true,
    pretask_url: null,
    is_pretask_visible: true,
    video_url: 'https://youtu.be/OILNU_cEpPg',
    is_video_visible: true,
    simulator_url: null,
    is_simulator_visible: true,
  },
  {
    name: 'Gerak Melingkar Beraturan I dan Gerak Melingkar Beraturan II',
    code: 'GMB',
    language: Language.ID,
    journal_cover_url:
      'https://docs.google.com/document/d/1z_tZSfLhBu3cw2GCuhqirxjhkhCoLrYw/edit?usp=sharing\u0026ouid=107672459749284549879\u0026rtpof=true\u0026sd=true',
    isActive: true,
    pretask_url:
      'https://drive.google.com/drive/u/5/folders/1aYQ7qx3oiMgXLWB0vRw9vTaJXS15EbdS',
    is_pretask_visible: true,
    video_url: 'https://youtu.be/C0lmsWzGBqY',
    is_video_visible: true,
    simulator_url:
      'https://drive.google.com/drive/folders/1oVPbxuB16yqYD2whalpanPLFVhSrTzkb?usp=sharing',
    is_simulator_visible: true,
  },
  {
    name: 'Uniform Circular Motion I and Uniform Circular Motion II',
    code: 'GMB',
    language: Language.EN,
    journal_cover_url: null,
    isActive: true,
    pretask_url: null,
    is_pretask_visible: true,
    video_url: 'https://youtu.be/L6kn35kZU3w',
    is_video_visible: true,
    simulator_url: null,
    is_simulator_visible: true,
  },
  {
    name: 'Gerak Osilasi dan Gerak Jatuh Bebas',
    code: 'GJB',
    language: Language.ID,
    journal_cover_url:
      'https://docs.google.com/document/d/1blUwtsf4zFicZY2eVJKw7ma79S-Vuhlc/edit?usp=sharing\u0026ouid=107672459749284549879\u0026rtpof=true\u0026sd=true',
    isActive: true,
    pretask_url:
      'https://drive.google.com/drive/u/5/folders/1wlFRuW7NdB8kSe3UI8jbluYCeOHouqnD',
    is_pretask_visible: true,
    video_url: 'https://youtu.be/_d7rTW_MJLk',
    is_video_visible: true,
    simulator_url:
      'https://drive.google.com/drive/folders/1NIzVokX7tqAzMtRML3qDn9QEFJ12QdD7?usp=sharing',
    is_simulator_visible: true,
  },
  {
    name: 'Oscillatory Motion and Free Fall Motion',
    code: 'GJB',
    language: Language.EN,
    journal_cover_url: null,
    isActive: true,
    pretask_url: null,
    is_pretask_visible: true,
    video_url: 'https://youtu.be/V5wuEmfOY6Y',
    is_video_visible: true,
    simulator_url: null,
    is_simulator_visible: true,
  },
  {
    name: 'Pendahuluan Listrik',
    code: 'PL',
    language: Language.ID,
    journal_cover_url:
      'https://docs.google.com/document/d/1gxv176-1qJlpb7Pmv7ZWPF3qu463vuJ2/edit?usp=sharing\u0026ouid=107672459749284549879\u0026rtpof=true\u0026sd=true',
    isActive: true,
    pretask_url: null,
    is_pretask_visible: true,
    video_url: 'https://youtu.be/tSoHDrNeR6s',
    is_video_visible: true,
    simulator_url:
      'https://drive.google.com/drive/folders/14cRqdv_RLZ3W2H0BJgFFyWWJ5CHowFO2?usp=sharing',
    is_simulator_visible: true,
  },
  {
    name: 'Introduction to Electricity',
    code: 'PL',
    language: Language.EN,
    journal_cover_url: null,
    isActive: true,
    pretask_url: null,
    is_pretask_visible: true,
    video_url: 'https://youtu.be/zFiOw0jBIAI',
    is_video_visible: true,
    simulator_url: null,
    is_simulator_visible: true,
  },
  {
    name: 'Superposisi Getaran Harmonik',
    code: 'SGH',
    language: Language.ID,
    journal_cover_url:
      'https://docs.google.com/document/d/1fEMhaP30NVBhQwNCduAdYBnIW3RSidDl/edit?usp=sharing\u0026ouid=107672459749284549879\u0026rtpof=true\u0026sd=true',
    isActive: true,
    pretask_url:
      'https://drive.google.com/drive/u/5/folders/16QuaMj6t4U1SeFu49U2eh0M7IkPPzNMS',
    is_pretask_visible: true,
    video_url: 'https://youtu.be/OcNuGpErbOI',
    is_video_visible: true,
    simulator_url:
      'https://drive.google.com/drive/folders/1yhLMytF9NYKvL-QRKtbCyiQ-63olC8gA?usp=sharing',
    is_simulator_visible: true,
  },
  {
    name: 'Superposition Of Harmonic Vibration',
    code: 'SGH',
    language: Language.EN,
    journal_cover_url: null,
    isActive: true,
    pretask_url: null,
    is_pretask_visible: true,
    video_url: 'https://youtu.be/KMWu69PPwnI',
    is_video_visible: true,
    simulator_url: 'https://academo.org/demos/virtual-oscilloscope/',
    is_simulator_visible: true,
  },
  {
    name: 'Pengukuran Besaran Listrik',
    code: 'PBL',
    language: Language.ID,
    journal_cover_url:
      'https://docs.google.com/document/d/1cqtHcjUIigmlepVWLdT3avG3548LqjS_/edit?usp=sharing\u0026ouid=107672459749284549879\u0026rtpof=true\u0026sd=true',
    isActive: true,
    pretask_url:
      'https://drive.google.com/drive/folders/1nKxxpkB3aL7IZCf1IbogstpS6vZGJslD?usp=sharing',
    is_pretask_visible: true,
    video_url: 'https://youtu.be/7rJ5rVlCTME',
    is_video_visible: true,
    simulator_url:
      'https://drive.google.com/drive/u/3/folders/1Z0hjR6zS6V7Mfkv4_KFvIsp3UlC4uvnK',
    is_simulator_visible: true,
  },
  {
    name: 'Measurement Of Electrical Quantities',
    code: 'PBL',
    language: Language.EN,
    journal_cover_url: null,
    isActive: true,
    pretask_url: null,
    is_pretask_visible: true,
    video_url: 'https://youtu.be/ONLbrO0oEUY',
    is_video_visible: true,
    simulator_url:
      'http://amrita.olabs.edu.in/?sub=1\u0026brch=4\u0026sim=99\u0026cnt=4',
    is_simulator_visible: true,
  },
  {
    name: 'GLBB, GLB, dan Momen Inersia',
    code: 'GLB',
    language: Language.ID,
    journal_cover_url:
      'https://docs.google.com/document/d/1E8zsxMuh36x1oxkNo6-ECH6SwgupCD0j/edit?usp=sharing\u0026ouid=107672459749284549879\u0026rtpof=true\u0026sd=true',
    isActive: true,
    pretask_url:
      'https://drive.google.com/drive/folders/1bu58kfgkqL1zyvjvNUQmC0z857JxOWni',
    is_pretask_visible: true,
    video_url: 'https://youtu.be/1j6FxITNOHE',
    is_video_visible: true,
    simulator_url:
      'https://drive.google.com/drive/folders/1qilx48q59XQbciOeg6AVK-ixlsFjLJNW?usp=sharing',
    is_simulator_visible: true,
  },
  {
    name: 'Uniform Accelerated Linear Motion, Uniform Linear Motion, and Pulley Inertia Moment',
    code: 'GLB',
    language: Language.EN,
    journal_cover_url: null,
    isActive: true,
    pretask_url: null,
    is_pretask_visible: true,
    video_url: 'https://youtu.be/bnsX7_u82WA',
    is_video_visible: true,
    simulator_url:
      'http://amrita.olabs.edu.in/?sub=1\u0026brch=1\u0026sim=44\u0026cnt=4',
    is_simulator_visible: true,
  },
  {
    name: 'Resonansi Gelombang Bunyi',
    code: 'RGB',
    language: Language.ID,
    journal_cover_url:
      'https://docs.google.com/document/d/1y1SdLnRyR1cDgUhcwFTY6DYvsc0eFMAr/edit?usp=sharing\u0026ouid=107672459749284549879\u0026rtpof=true\u0026sd=true',
    isActive: true,
    pretask_url:
      'https://drive.google.com/drive/u/5/folders/1gDvtCkVF5eEVm7kZ3DPgSNJ7nARYZZRK',
    is_pretask_visible: true,
    video_url: 'https://youtu.be/l7Z_9Rp30m4',
    is_video_visible: true,
    simulator_url:
      'https://drive.google.com/drive/folders/1srDKIMKO50nAl9vTjtEMw-qswdmRhr5W?usp=sharing',
    is_simulator_visible: true,
  },
  {
    name: 'Resonance of Sound Waves',
    code: 'RGB',
    language: Language.EN,
    journal_cover_url: null,
    isActive: true,
    pretask_url: null,
    is_pretask_visible: true,
    video_url: 'https://youtu.be/i01m1jeWbW0',
    is_video_visible: true,
    simulator_url:
      'http://amrita.olabs.edu.in/?sub=1\u0026brch=5\u0026sim=36\u0026cnt=4',
    is_simulator_visible: true,
  },

  {
    name: 'Induksi Magnetik',
    code: 'IM',
    language: Language.ID,
    journal_cover_url:
      'https://docs.google.com/document/d/12j74CNeRBZ_nA-7OO9X0OkivjgFo3xkw/edit?usp=sharing\u0026ouid=107672459749284549879\u0026rtpof=true\u0026sd=true',
    isActive: true,
    pretask_url:
      'https://drive.google.com/drive/folders/1k483_3CueLh1nVhsWkBt_rHOObA8_obD?usp=sharing',
    is_pretask_visible: true,
    video_url: 'https://youtu.be/ffVD-vI2hzc',
    is_video_visible: true,
    simulator_url:
      'https://drive.google.com/drive/folders/1GgsM3nPr1J4GusDE4bx7G6l6J0tSdVgT?usp=sharing',
    is_simulator_visible: true,
  },
  {
    name: 'Magnetic Induction',
    code: 'IM',
    language: Language.EN,
    journal_cover_url: null,
    isActive: true,
    pretask_url: null,
    is_pretask_visible: true,
    video_url: 'https://youtu.be/IhblFR5Z00k',
    is_video_visible: true,
    simulator_url:
      'http://cdac.olabs.edu.in/?sub=74\u0026brch=9\u0026sim=242\u0026cnt=4',
    is_simulator_visible: true,
  },
  {
    name: 'Pengisian dan Pengosongan Kapasitor',
    code: 'KAP',
    language: Language.ID,
    journal_cover_url:
      'https://docs.google.com/document/d/1FQzUj9wdQsDSALYiuqgHJvlEMxWpw22I/edit?usp=sharing\u0026ouid=107672459749284549879\u0026rtpof=true\u0026sd=true',
    isActive: true,
    pretask_url:
      'https://drive.google.com/drive/folders/1AcLW0yVp_jblg7EcPpu9FDdoChQufb38?usp=sharing',
    is_pretask_visible: true,
    video_url: 'https://youtu.be/-u71VfZc6uw',
    is_video_visible: true,
    simulator_url:
      'https://drive.google.com/drive/folders/1Q8bcv5pcVx3TuaiIKmG9iDYQb_bhCAve?usp=sharing',
    is_simulator_visible: true,
  },
  {
    name: 'Charging and Discharging Capacitors',
    code: 'KAP',
    language: Language.EN,
    journal_cover_url: null,
    isActive: true,
    pretask_url: null,
    is_pretask_visible: true,
    video_url: 'https://youtu.be/EEVoWxOr520',
    is_video_visible: true,
    simulator_url: null,
    is_simulator_visible: true,
  },
  {
    name: 'Jembatan Wheatstone',
    code: 'JW',
    language: Language.ID,
    journal_cover_url:
      'https://docs.google.com/document/d/1cbi2wzNi0HwoaFM1a7MuzJfk-VitQCdw/edit?usp=sharing\u0026ouid=107672459749284549879\u0026rtpof=true\u0026sd=true',
    isActive: true,
    pretask_url:
      'https://drive.google.com/drive/folders/1MvdoxnB9DSQpscfYzZIq8crGWw8X_NcO?usp=sharing',
    is_pretask_visible: true,
    video_url: 'https://youtu.be/PGhqCtgiRz4',
    is_video_visible: true,
    simulator_url:
      'https://drive.google.com/drive/folders/1_SO0oBqgQrzY61_p0eQekUWUb_PYxYpf?usp=sharing',
    is_simulator_visible: true,
  },
  {
    name: 'Wheatstone Bridge',
    code: 'JW',
    language: Language.EN,
    journal_cover_url: null,
    isActive: true,
    pretask_url: null,
    is_pretask_visible: true,
    video_url: 'https://youtu.be/4NWxCnmg6ho',
    is_video_visible: true,
    simulator_url: null,
    is_simulator_visible: true,
  },
];
