name: Development

on:
  push:
    branches:
      - dev

env:
  working-directory: .

jobs:
  deploy:
    name: Deploy to Zuserver
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy
        env:
          SERVER_HOST: ${{ secrets.ZUSERVER_HOST }}
          SERVER_SSH_PRIVATE_KEY: ${{ secrets.ZUSERVER_SSH_PRIVATE_KEY }}
          SCRIPT: ${{ vars.ZUSERVER_DEPLOY_COMMAND }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
          echo "$SERVER_SSH_PRIVATE_KEY" > ~/.ssh/id_private_key
          chmod 600 ~/.ssh/id_private_key
          ssh -i ~/.ssh/id_private_key root@$SERVER_HOST "$SCRIPT"
      - name: Notify Discord
        if: ${{ !cancelled() }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "content": "**[DEPLOYMENT ${{ job.status == 'success' && 'SUCCESS' || 'FAILED' }}]**

            Project: Fisdasweb API
            Branch: `${{ github.ref_name }}`
            Job: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}
          }' ${{ secrets.DISCORD_WEBHOOK }}
