name: Revamp

on:
  push:
    branches:
      - revamp

env:
  working-directory: .

jobs:
  deploy:
    name: Deploy to Zuserver
    runs-on: ubuntu-latest
    environment: revamp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy
        env:
          SERVER_HOST: ${{ secrets.ZUSERVER_HOST }}
          SERVER_SSH_PRIVATE_KEY: ${{ secrets.ZUSERVER_SSH_PRIVATE_KEY }}
          SCRIPT: ${{ vars.ZUSERVER_DEPLOY_COMMAND }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
          echo "$SERVER_SSH_PRIVATE_KEY" > ~/.ssh/id_private_key
          chmod 600 ~/.ssh/id_private_key
          ssh -i ~/.ssh/id_private_key root@$SERVER_HOST "$SCRIPT"
